version: "3.8"
services:
  fampay_backend:
    container_name: fampay_backend
    image: jugaldb/fampay-backend:latest
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER=$USER
      - PASSWORD=$PASSWORD
      - DB=$DB
      - HOST=host.docker.internal # NAME OF THE SERVICE
      - DIALECT=$DIALECT
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
    depends_on:
      - fampay_db
  fampay_db:
    container_name: fampay_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jugaldb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jugaldb
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}
